<a href="https://colab.research.google.com/github/00FFEF/test_python/blob/master/python_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1

if cylinders == 3:
  cylinder = np.array([1,0,0,0,0])
elif cylinders == 4:
  cylinder = np.array([0,1,0,0,0])
elif cylinders == 5:
  cylinder = np.array([0,0,1,0,0])
elif cylinders == 6:
  cylinder = np.array([0,0,0,1,0])
elif cylinders == 8:
  cylinder = np.array([0,0,0,0,1])


x_continus = np.array([displacement, horsepower, weight, accel])
# cylinder = np.array([0,0,0,0,1])
org = np.array([1,0,0])

In [ ]:
type(x_continus), type(cylinder), type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
cylinder

array([0, 0, 0, 0, 1])

In [ ]:
result = np.concatenate((x_continus, cylinder, org), axis=None)
result.shape, result


((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [ ]:
# result.reshape(1,12)
result = result.reshape(-1, result.size)
result, result.shape, result.size

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12),
 12)

# function 이해

In [ ]:
21 + 14

35

In [ ]:
32 + 45

77

In [ ]:
def sum():
  first = 32
  second = 45
  result = first + second
  return result

In [ ]:
sum()

77

In [ ]:
f01 = 32
s02 = 21
def sum(f01, s02):
  first = s02
  second = f01
  result = first + second
  return result, second, first

In [ ]:
r1, r2, r3 = sum(21,564)
r1, r2, r3

(585, 21, 564)

In [ ]:
sum(32,21), sum(3,2), sum(21,564)

((53, 32), (5, 3), (585, 21))

In [ ]:
21 * 32 * 2

1344

In [ ]:
31 * 63 * 41

80073

In [ ]:
def mult(s1, s2, s3):
  result = s1 * s2 * s3
  return result

In [ ]:
mult(3, 4, 5)

60

In [ ]:
# def differenceVars(*var01, **args02)
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result01 = len(var_list)
  return result01

In [ ]:
diffparam(1,2,3,5,6,c=5,d=6,a=2,b=3)

{'c': 5, 'd': 6, 'a': 2, 'b': 3}


5

In [ ]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder = np.array([0,0,0,1,0])
  elif cylinders == 8:
    cylinder = np.array([0,0,0,0,1])
  return cylinder

In [ ]:
onehotcylinder(4), onehotcylinder(6)

(array([0, 1, 0, 0, 0]), array([0, 0, 0, 1, 0]))

In [ ]:
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1

onehotcylinder(cylinders)

x_continus = np.array([displacement, horsepower, weight, accel])
# cylinder = np.array([0,0,0,0,1])
cylinder = onehotcylinder(cylinders)
org = np.array([1,0,0])

In [ ]:
result = np.concatenate((x_continus, cylinder, org), axis=None)
result.shape, result

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [ ]:
result = result.reshape(-1, result.size)
result, result.shape, result.size

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12),
 12)